/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.Student;


import swing.*;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.example.Controller;

/**
 *
 * @author black
 */
public class StudentDashBoard extends javax.swing.JFrame {
    // tab components
    ScoresTabs scoresTabs = new ScoresTabs();
    RemarkStudentTabs remarkTabs = new RemarkStudentTabs();
    ChangePasswordTabs changePasswordTabs = new ChangePasswordTabs();

    JPanel[] listComponentPanel = new JPanel[] { scoresTabs, remarkTabs, changePasswordTabs};
    JPanel[] listTabPanel;

    
    String currentTabs = "tab_class";
    
    Color tab_background_color = new Color(23,35,51);
    Color tab_press_color = new Color(102,102,102);
    
    int tabWidth = 0;

    /**
     * Creates new form Home
     */
    public StudentDashBoard() {
        
        initComponents();
        this.setLocation(200, 50);


        tabWidth = tab_bar_student.getSize().width;
        listTabPanel = new JPanel [] {tab_score, tab_change_password, tab_remark, tab_logout};
                
        initTabComponent();

    }
    
    private void initTabComponent() {
        this.currentTabs = "tab_score";
        resetAllColor(tab_score);
        
        for (int i = 0; i < listComponentPanel.length; i++) {
            getContentPane().add(listComponentPanel[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 0, 830, 647));
        }
        setVisibleTabs(scoresTabs);
        
        
        
        pack();
    }
    
    private void setColor(JPanel panel) {
        panel.setBackground(this.tab_press_color);
    }
    
    private void resetColor(JPanel panel) {
        panel.setBackground(this.tab_background_color);
    }
    
    private void resetAllColor(JPanel current) {
        for(int i = 0; i < listTabPanel.length; i++) {
            if(listTabPanel[i] == current) {
                continue;
            }
            listTabPanel[i].setBackground(this.tab_background_color);
        }
    }
    
    private void setVisibleTabs(JPanel panel) {
        for (int i = 0; i < listComponentPanel.length; i++) {
            JPanel p = listComponentPanel[i];
            if(p == panel) {
                p.setVisible(true);
            }
            else {
                p.setVisible(false);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_bar_student = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        tab_score = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tab_remark = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tab_remark5 = new javax.swing.JPanel();
        tab_remark6 = new javax.swing.JPanel();
        tab_remark7 = new javax.swing.JPanel();
        tab_remark8 = new javax.swing.JPanel();
        tab_change_password = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tab_logout = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_bar_student.setBackground(new java.awt.Color(23, 35, 51));
        tab_bar_student.setPreferredSize(new java.awt.Dimension(300, 650));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Quản Lý Học Tập");
        jLabel12.setToolTipText("");

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(8, 0));

        tab_score.setBackground(new java.awt.Color(102, 102, 102));
        tab_score.setAlignmentX(15.0F);
        tab_score.setAlignmentY(15.0F);
        tab_score.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_score.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_scoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_scoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_scoreMouseExited(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-7-24.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Kết quả học tập");

        javax.swing.GroupLayout tab_scoreLayout = new javax.swing.GroupLayout(tab_score);
        tab_score.setLayout(tab_scoreLayout);
        tab_scoreLayout.setHorizontalGroup(
            tab_scoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_scoreLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_scoreLayout.setVerticalGroup(
            tab_scoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_score);

        tab_remark.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark.setAlignmentX(15.0F);
        tab_remark.setAlignmentY(15.0F);
        tab_remark.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_remarkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_remarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_remarkMouseExited(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo-2-24.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Phúc khảo");

        javax.swing.GroupLayout tab_remarkLayout = new javax.swing.GroupLayout(tab_remark);
        tab_remark.setLayout(tab_remarkLayout);
        tab_remarkLayout.setHorizontalGroup(
            tab_remarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_remarkLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_remarkLayout.setVerticalGroup(
            tab_remarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark);

        tab_remark5.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark5.setAlignmentX(15.0F);
        tab_remark5.setAlignmentY(15.0F);
        tab_remark5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark5.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark5.setOpaque(false);

        javax.swing.GroupLayout tab_remark5Layout = new javax.swing.GroupLayout(tab_remark5);
        tab_remark5.setLayout(tab_remark5Layout);
        tab_remark5Layout.setHorizontalGroup(
            tab_remark5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark5Layout.setVerticalGroup(
            tab_remark5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark5);

        tab_remark6.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark6.setAlignmentX(15.0F);
        tab_remark6.setAlignmentY(15.0F);
        tab_remark6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark6.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark6.setOpaque(false);

        javax.swing.GroupLayout tab_remark6Layout = new javax.swing.GroupLayout(tab_remark6);
        tab_remark6.setLayout(tab_remark6Layout);
        tab_remark6Layout.setHorizontalGroup(
            tab_remark6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark6Layout.setVerticalGroup(
            tab_remark6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark6);

        tab_remark7.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark7.setAlignmentX(15.0F);
        tab_remark7.setAlignmentY(15.0F);
        tab_remark7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark7.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark7.setOpaque(false);

        javax.swing.GroupLayout tab_remark7Layout = new javax.swing.GroupLayout(tab_remark7);
        tab_remark7.setLayout(tab_remark7Layout);
        tab_remark7Layout.setHorizontalGroup(
            tab_remark7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark7Layout.setVerticalGroup(
            tab_remark7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark7);

        tab_remark8.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark8.setAlignmentX(15.0F);
        tab_remark8.setAlignmentY(15.0F);
        tab_remark8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark8.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark8.setOpaque(false);

        javax.swing.GroupLayout tab_remark8Layout = new javax.swing.GroupLayout(tab_remark8);
        tab_remark8.setLayout(tab_remark8Layout);
        tab_remark8Layout.setHorizontalGroup(
            tab_remark8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark8Layout.setVerticalGroup(
            tab_remark8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark8);

        tab_change_password.setBackground(new java.awt.Color(102, 102, 102));
        tab_change_password.setAlignmentX(15.0F);
        tab_change_password.setAlignmentY(15.0F);
        tab_change_password.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_change_password.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_change_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_change_passwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_change_passwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_change_passwordMouseExited(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock-24.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Đổi mật khẩu");

        javax.swing.GroupLayout tab_change_passwordLayout = new javax.swing.GroupLayout(tab_change_password);
        tab_change_password.setLayout(tab_change_passwordLayout);
        tab_change_passwordLayout.setHorizontalGroup(
            tab_change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_change_passwordLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_change_passwordLayout.setVerticalGroup(
            tab_change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_change_password);

        tab_logout.setBackground(new java.awt.Color(102, 102, 102));
        tab_logout.setAlignmentX(15.0F);
        tab_logout.setAlignmentY(15.0F);
        tab_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_logout.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_logoutMouseExited(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x-mark-24.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Đăng xuất");

        javax.swing.GroupLayout tab_logoutLayout = new javax.swing.GroupLayout(tab_logout);
        tab_logout.setLayout(tab_logoutLayout);
        tab_logoutLayout.setHorizontalGroup(
            tab_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_logoutLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_logoutLayout.setVerticalGroup(
            tab_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_logout);

        javax.swing.GroupLayout tab_bar_studentLayout = new javax.swing.GroupLayout(tab_bar_student);
        tab_bar_student.setLayout(tab_bar_studentLayout);
        tab_bar_studentLayout.setHorizontalGroup(
            tab_bar_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bar_studentLayout.createSequentialGroup()
                .addGroup(tab_bar_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_bar_studentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        tab_bar_studentLayout.setVerticalGroup(
            tab_bar_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bar_studentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        getContentPane().add(tab_bar_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        int h = evt.getComponent().getBounds().getSize().height;
        Dimension d = new Dimension(tabWidth, h);
        tab_bar_student.setSize(d);
        
    }//GEN-LAST:event_formComponentResized

    private void tab_scoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scoreMouseClicked
        // TODO add your handling code here:
        setVisibleTabs(scoresTabs);
        setColor(tab_score);
        resetAllColor(tab_score);
        this.currentTabs = "tab_score";
        pack();
    }//GEN-LAST:event_tab_scoreMouseClicked

    private void tab_scoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scoreMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_score")) {
            return;
        }
        setColor(tab_score);
    }//GEN-LAST:event_tab_scoreMouseEntered

    private void tab_scoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scoreMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_score")) {
            return;
        }
        resetColor(tab_score);
    }//GEN-LAST:event_tab_scoreMouseExited

    private void tab_remarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remarkMouseClicked
        // TODO add your handling code here:
        setVisibleTabs(remarkTabs);
        setColor(tab_remark);
        resetAllColor(tab_remark);
        this.currentTabs = "tab_remark";
        pack();
    }//GEN-LAST:event_tab_remarkMouseClicked

    private void tab_remarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remarkMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_remark")) {
            return;
        }
        setColor(tab_remark);
    }//GEN-LAST:event_tab_remarkMouseEntered

    private void tab_remarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remarkMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_remark")) {
            return;
        }
        resetColor(tab_remark);
    }//GEN-LAST:event_tab_remarkMouseExited

    private void tab_change_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_change_passwordMouseClicked
        // TODO add your handling code here:
         setVisibleTabs(changePasswordTabs);
        setColor(tab_change_password);
        resetAllColor(tab_change_password);
        this.currentTabs = "tab_change_password";
        pack();
    }//GEN-LAST:event_tab_change_passwordMouseClicked

    private void tab_change_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_change_passwordMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_change_password")) {
            return;
        }
        setColor(tab_change_password);
    }//GEN-LAST:event_tab_change_passwordMouseEntered

    private void tab_change_passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_change_passwordMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_change_password")) {
            return;
        }
        resetColor(tab_change_password);
    }//GEN-LAST:event_tab_change_passwordMouseExited

    private void tab_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logoutMouseClicked
        // TODO add your handling code here:
        Controller.user = null;
        Controller.handleLogin();
    }//GEN-LAST:event_tab_logoutMouseClicked

    private void tab_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logoutMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_logout")) {
            return;
        }
        setColor(tab_logout);
    }//GEN-LAST:event_tab_logoutMouseEntered

    private void tab_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logoutMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_logout")) {
            return;
        }
        resetColor(tab_logout);
    }//GEN-LAST:event_tab_logoutMouseExited

    

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel tab_bar_student;
    private javax.swing.JPanel tab_change_password;
    private javax.swing.JPanel tab_logout;
    private javax.swing.JPanel tab_remark;
    private javax.swing.JPanel tab_remark5;
    private javax.swing.JPanel tab_remark6;
    private javax.swing.JPanel tab_remark7;
    private javax.swing.JPanel tab_remark8;
    private javax.swing.JPanel tab_score;
    // End of variables declaration//GEN-END:variables
}
