/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.Dialog;

import java.util.Iterator;
import java.util.List;
import model.ClassesEntity;
import model.ScoresEntity;
import model.StudentsEntity;
import model.SubjectsEntity;
import dao.*;
import java.awt.Container;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author black
 */
public class UpdateScore extends javax.swing.JDialog {
     ScoreDao scoreDao = new ScoreDao();
     ClassesDao classesDao = new ClassesDao();
     Container f = this;
     StudentsEntity s = new StudentsEntity();
     ScoresEntity score = new ScoresEntity();
     List<StudentsEntity> listStudent;
     boolean loading = false;

     final String GK = "Điểm giữa kỳ";
    final String CK = "Điểm cuối kỳ";
    final String OTHER = "Điểm Khác";
    final String TOTAL = "Điểm Tổng";
    int field = -1;

    /**
     * Creates new form AddStudent
     */
    public UpdateScore() {
        initComponents();
        
        initSelectBoxData();
        score_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"",GK, CK, OTHER, TOTAL}));
    }
    
    void initSelectBoxData() {
        List<ClassesEntity> classesName = classesDao.getListClass();
        if(classesName == null || classesName.size() == 0) {
            class_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
            initSubjectData();
            return;
        }
        String[] name = new String[classesName.size()];
        for (int i = 0; i < classesName.size(); i++) {
            name[i] = classesName.get(i).getClassId();
        }
        class_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(name));
        initSubjectData();
    }

    void initSubjectData() {
        String classID = (String) class_select_box.getSelectedItem();
        List<String> listsubject = scoreDao.getListSubject(classID);
        if(classID == null || classID.equals("") || listsubject == null || listsubject.size() == 0) {
            subject_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
            initStudentData();
            return;
        }
        String[] subject = new String[listsubject.size()];
        listsubject.toArray(subject);
        subject_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(subject));
        initStudentData();
    }

    void initStudentData() {
        String classID = (String) class_select_box.getSelectedItem();
        String subjectID = (String) subject_select_box.getSelectedItem();
        if(classID == null || classID.equals("") || subjectID == null || subjectID.equals("")) {
            student_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
            return;
        }
        listStudent = classesDao.danhsachmon(classID, subjectID);
        if(listStudent == null || listStudent.size() == 0) {
            student_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
            return;
        }
        String[] student = new String[listStudent.size() + 1];
        student[0] = "";
        for(int i = 0; i <listStudent.size(); i++) {
            student[i + 1] = listStudent.get(i).getStudentId();
        }
        student_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(student));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        class_select_box = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        subject_select_box = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edt_new_score = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btn_submit = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        student_select_box = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        score_select_box = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        edt_name = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        edt_old_score = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm  sinh viên");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);
        jPanel2.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Chọn mã lớp:");

        class_select_box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        class_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        class_select_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_select_boxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Chọn mã môn:");

        subject_select_box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subject_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        subject_select_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_select_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(class_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(subject_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Số điểm mới:");

        edt_new_score.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edt_new_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_new_scoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(edt_new_score)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_new_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_submit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_submit.setText("Xác nhận");
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Chọn mã học sinh:");

        student_select_box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        student_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        student_select_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_select_boxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Chọn cột điểm:");

        score_select_box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        score_select_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        score_select_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score_select_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(student_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(score_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(student_select_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Họ và tên:");

        edt_name.setEditable(false);
        edt_name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edt_name)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Số điểm hiện tại:");

        edt_old_score.setEditable(false);
        edt_old_score.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edt_old_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_old_scoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edt_old_score)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_old_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edt_new_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_new_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_new_scoreActionPerformed

    class AddStudentThread extends Thread {
        public void run() {
            try {
                String classID = (String) class_select_box.getSelectedItem();
                String subjectID = (String) subject_select_box.getSelectedItem();
                String newScore = edt_new_score.getText();
                Double newScoreDouble = Double.parseDouble(newScore);
                String studentID = (String) student_select_box.getSelectedItem();
                String info = "";
                switch (field) {
                    case 0:
                        info = scoreDao.editScore(studentID, classID, subjectID, newScoreDouble, score.getEndTermScore(), score.getOtherScore(), score.getTotalScore());

                        break;
                    case 1:
                        info = scoreDao.editScore(studentID, classID, subjectID, score.getMidTermScore(), newScoreDouble, score.getOtherScore(), score.getTotalScore());
                        break;
                    case 2:
                        info = scoreDao.editScore(studentID, classID, subjectID, score.getMidTermScore(), score.getEndTermScore(), newScoreDouble, score.getTotalScore());
                        break;
                    case 3:
                        info = scoreDao.editScore(studentID, classID, subjectID, score.getMidTermScore(), score.getEndTermScore(), score.getOtherScore(), newScoreDouble);
                        break;
                }
                List result = scoreDao.xemdiem(classID,subjectID, studentID);
                Iterator itr = result.iterator();

                while (itr.hasNext()) {
                    Object[] obj = (Object[]) itr.next();
                    score = (ScoresEntity) obj[0];
                }
                btn_submit.setIcon(null);
                loading = false;
                JOptionPane.showMessageDialog(f.getParent(), info);
                if(info == ClassesDao.CLASSES_SUCCESS) {
                    edt_new_score.setText("");
                }
            }catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    
    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        if(loading) {
            return;
        }
        String newScore = edt_new_score.getText();

        String studentID = (String) student_select_box.getSelectedItem();
        String scoreField = (String) score_select_box.getSelectedItem();
        String classID = (String) class_select_box.getSelectedItem();
        String subjectID = (String) subject_select_box.getSelectedItem();

        if(classID==null || studentID == null || subjectID == null || newScore.length() == 0 || studentID.equals("")
                || scoreField.equals("") || classID.equals("") || subjectID.equals("")) {
            JOptionPane.showMessageDialog(evt.getComponent().getParent().getParent(), "Dữ liệu không hợp lệ!");
            return;
        }
        try{
            Double newScoreDouble = Double.parseDouble(newScore);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(evt.getComponent().getParent().getParent(), "Dữ liệu không hợp lệ!");
            return;
        }

        loading = true;
        ClassLoader cldr = this.getClass().getClassLoader();
        java.net.URL imageURL   = cldr.getResource("Rolling-1s-32px.gif");
        ImageIcon img = new ImageIcon(imageURL);
        btn_submit.setIcon(img);
        AddStudentThread add = new AddStudentThread();
        add.start();
    }//GEN-LAST:event_btn_submitMouseClicked

    private void edt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_nameActionPerformed

    private void edt_old_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_old_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_old_scoreActionPerformed

    private void class_select_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_select_boxActionPerformed
        // TODO add your handling code here:
        if(loading) {
            return;
        }
        student_select_box.setSelectedItem("");
        score_select_box.setSelectedItem("");
        edt_name.setText("");
        edt_old_score.setText("");
        initSubjectData();
    }//GEN-LAST:event_class_select_boxActionPerformed

    private void subject_select_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_select_boxActionPerformed
        // TODO add your handling code here:
        if(loading) {
            return;
        }
        student_select_box.setSelectedItem("");
        score_select_box.setSelectedItem("");
        edt_name.setText("");
        edt_old_score.setText("");
        initStudentData();

    }//GEN-LAST:event_subject_select_boxActionPerformed

    private void student_select_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_select_boxActionPerformed
        // TODO add your handling code here:
        if(loading) {
            return;
        }
        String studentID = (String) student_select_box.getSelectedItem();
        if(studentID.equals("")) {
            s = new StudentsEntity();
            edt_name.setText("");
            score_select_box.setSelectedItem("");
            edt_old_score.setText("");
            return;
        }
        if(listStudent == null) {
            return;
        }
        String classID = (String) class_select_box.getSelectedItem();
        String subjectID = (String) subject_select_box.getSelectedItem();

        List result = scoreDao.xemdiem(classID,subjectID, studentID);
        if(result.size() == 0) {
            JOptionPane.showMessageDialog(f.getParent().getParent(), "Học Sinh chưa có điểm");
            student_select_box.setSelectedItem("");
            return;
        }
        Iterator itr = result.iterator();

        while (itr.hasNext()) {
            Object[] obj = (Object[]) itr.next();
            score = (ScoresEntity) obj[0];
        }

        for(int i = 0; i< listStudent.size(); i++) {
            if(studentID.equals(listStudent.get(i).getStudentId())) {
                s = listStudent.get(i);
                edt_name.setText(s.getName());
                return;
            }
        }

    }//GEN-LAST:event_student_select_boxActionPerformed

    private void score_select_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score_select_boxActionPerformed
        // TODO add your handling code here:
        if(loading) {
            return;
        }
        String selected = (String) score_select_box.getSelectedItem();
        if(!selected.equals("") && score != null) {
            if(selected.equals(GK)) {
                edt_old_score.setText(score.getMidTermScore()+ "");
                field = 0;
            }
            else if(selected.equals(CK)) {
                edt_old_score.setText(score.getEndTermScore()+ "");
                field = 1;
            }
            else if(selected.equals(OTHER)) {
                edt_old_score.setText(score.getOtherScore()+ "");
                field = 2;
            }
            else {
                edt_old_score.setText(score.getTotalScore()+ "");
                field = 3;
            }
        }
        else {
            edt_old_score.setText("");
            field = -1;
        }
    }//GEN-LAST:event_score_select_boxActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> class_select_box;
    private javax.swing.JTextField edt_name;
    private javax.swing.JTextField edt_new_score;
    private javax.swing.JTextField edt_old_score;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> score_select_box;
    private javax.swing.JComboBox<String> student_select_box;
    private javax.swing.JComboBox<String> subject_select_box;
    // End of variables declaration//GEN-END:variables
}
