/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;


import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.example.Controller;

/**
 *
 * @author black
 */
public class Home extends javax.swing.JFrame {
    // tab components
    ClassTabs classTabs = new ClassTabs();
    ScheduleTabs scheduleTabs = new ScheduleTabs();
    StudentTabs studentTabs = new StudentTabs();
    ScoresTabs scoresTabs = new ScoresTabs();
    RemarkTabs remarkTabs = new RemarkTabs();
    
    JPanel[] listComponentPanel = new JPanel[] {classTabs, scheduleTabs, studentTabs, scoresTabs, remarkTabs};
    JPanel[] listTabPanel;

    
    String currentTabs = "tab_class";
    
    Color tab_background_color = new Color(23,35,51);
    Color tab_press_color = new Color(102,102,102);
    
    int tabWidth = 0;

    boolean studentType = Controller.user.getUsertype() == 0 ? true : false;

    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
        tabWidth = tab_bar_teacher.getSize().width;
        listTabPanel = new JPanel [] {tab_class, tab_schedule, tab_student, tab_score, tab_remark, tab_logout};
                
        initTabComponent();

    }
    
    private void initTabComponent() {
        this.currentTabs = "tab_class";
        resetAllColor(tab_class);
        
        for (int i = 0; i < listComponentPanel.length; i++) {
            getContentPane().add(listComponentPanel[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 0, 830, 647));
        }
        setVisibleTabs(classTabs);
        
        
        
        pack();
    }
    
    private void setColor(JPanel panel) {
        panel.setBackground(this.tab_press_color);
    }
    
    private void resetColor(JPanel panel) {
        panel.setBackground(this.tab_background_color);
    }
    
    private void resetAllColor(JPanel current) {
        for(int i = 0; i < listTabPanel.length; i++) {
            if(listTabPanel[i] == current) {
                continue;
            }
            listTabPanel[i].setBackground(this.tab_background_color);
        }
    }
    
    private void setVisibleTabs(JPanel panel) {
        for (int i = 0; i < listComponentPanel.length; i++) {
            JPanel p = listComponentPanel[i];
            if(p == panel) {
                p.setVisible(true);
            }
            else {
                p.setVisible(false);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_bar_teacher = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        tab_class = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tab_schedule = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tab_student = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tab_score = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tab_remark = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tab_remark1 = new javax.swing.JPanel();
        teacher_change_pass = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tab_logout = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tab_bar_student = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        tab_class1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tab_class2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tab_remark3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tab_remark5 = new javax.swing.JPanel();
        tab_remark6 = new javax.swing.JPanel();
        tab_remark7 = new javax.swing.JPanel();
        ChangePassword = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tab_logout2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_bar_teacher.setBackground(new java.awt.Color(23, 35, 51));
        tab_bar_teacher.setPreferredSize(new java.awt.Dimension(300, 650));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Sinh Viên");
        jLabel1.setToolTipText("");

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(8, 0));

        tab_class.setBackground(new java.awt.Color(102, 102, 102));
        tab_class.setAlignmentX(15.0F);
        tab_class.setAlignmentY(15.0F);
        tab_class.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_class.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_class.setPreferredSize(new java.awt.Dimension(64, 64));
        tab_class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_classMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_classMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_classMouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Danh sách lớp");

        javax.swing.GroupLayout tab_classLayout = new javax.swing.GroupLayout(tab_class);
        tab_class.setLayout(tab_classLayout);
        tab_classLayout.setHorizontalGroup(
            tab_classLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_classLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_classLayout.setVerticalGroup(
            tab_classLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel5.add(tab_class);
        tab_class.getAccessibleContext().setAccessibleName("");

        tab_schedule.setBackground(new java.awt.Color(102, 102, 102));
        tab_schedule.setAlignmentX(15.0F);
        tab_schedule.setAlignmentY(15.0F);
        tab_schedule.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_schedule.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_scheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_scheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_scheduleMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schedule_icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Thời khóa biểu");

        javax.swing.GroupLayout tab_scheduleLayout = new javax.swing.GroupLayout(tab_schedule);
        tab_schedule.setLayout(tab_scheduleLayout);
        tab_scheduleLayout.setHorizontalGroup(
            tab_scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_scheduleLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_scheduleLayout.setVerticalGroup(
            tab_scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel5.add(tab_schedule);

        tab_student.setBackground(new java.awt.Color(102, 102, 102));
        tab_student.setAlignmentX(15.0F);
        tab_student.setAlignmentY(15.0F);
        tab_student.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_student.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_studentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_studentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_studentMouseExited(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Sinh viên");

        javax.swing.GroupLayout tab_studentLayout = new javax.swing.GroupLayout(tab_student);
        tab_student.setLayout(tab_studentLayout);
        tab_studentLayout.setHorizontalGroup(
            tab_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_studentLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_studentLayout.setVerticalGroup(
            tab_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel5.add(tab_student);

        tab_score.setBackground(new java.awt.Color(102, 102, 102));
        tab_score.setAlignmentX(15.0F);
        tab_score.setAlignmentY(15.0F);
        tab_score.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_score.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_scoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_scoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_scoreMouseExited(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/score-icon.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Điểm số");

        javax.swing.GroupLayout tab_scoreLayout = new javax.swing.GroupLayout(tab_score);
        tab_score.setLayout(tab_scoreLayout);
        tab_scoreLayout.setHorizontalGroup(
            tab_scoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_scoreLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_scoreLayout.setVerticalGroup(
            tab_scoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel5.add(tab_score);

        tab_remark.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark.setAlignmentX(15.0F);
        tab_remark.setAlignmentY(15.0F);
        tab_remark.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_remarkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_remarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_remarkMouseExited(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaint_icon.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Phúc khảo");

        javax.swing.GroupLayout tab_remarkLayout = new javax.swing.GroupLayout(tab_remark);
        tab_remark.setLayout(tab_remarkLayout);
        tab_remarkLayout.setHorizontalGroup(
            tab_remarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_remarkLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_remarkLayout.setVerticalGroup(
            tab_remarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel5.add(tab_remark);

        tab_remark1.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark1.setAlignmentX(15.0F);
        tab_remark1.setAlignmentY(15.0F);
        tab_remark1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark1.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark1.setOpaque(false);

        javax.swing.GroupLayout tab_remark1Layout = new javax.swing.GroupLayout(tab_remark1);
        tab_remark1.setLayout(tab_remark1Layout);
        tab_remark1Layout.setHorizontalGroup(
            tab_remark1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark1Layout.setVerticalGroup(
            tab_remark1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel5.add(tab_remark1);

        teacher_change_pass.setBackground(new java.awt.Color(102, 102, 102));
        teacher_change_pass.setAlignmentX(15.0F);
        teacher_change_pass.setAlignmentY(15.0F);
        teacher_change_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        teacher_change_pass.setMinimumSize(new java.awt.Dimension(64, 64));
        teacher_change_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher_change_passMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacher_change_passMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacher_change_passMouseExited(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_icon.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Đổi mật khẩu");

        javax.swing.GroupLayout teacher_change_passLayout = new javax.swing.GroupLayout(teacher_change_pass);
        teacher_change_pass.setLayout(teacher_change_passLayout);
        teacher_change_passLayout.setHorizontalGroup(
            teacher_change_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacher_change_passLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        teacher_change_passLayout.setVerticalGroup(
            teacher_change_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel5.add(teacher_change_pass);

        tab_logout.setBackground(new java.awt.Color(102, 102, 102));
        tab_logout.setAlignmentX(15.0F);
        tab_logout.setAlignmentY(15.0F);
        tab_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_logout.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_logoutMouseExited(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_icon.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Đăng xuất");

        javax.swing.GroupLayout tab_logoutLayout = new javax.swing.GroupLayout(tab_logout);
        tab_logout.setLayout(tab_logoutLayout);
        tab_logoutLayout.setHorizontalGroup(
            tab_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_logoutLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_logoutLayout.setVerticalGroup(
            tab_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel5.add(tab_logout);

        javax.swing.GroupLayout tab_bar_teacherLayout = new javax.swing.GroupLayout(tab_bar_teacher);
        tab_bar_teacher.setLayout(tab_bar_teacherLayout);
        tab_bar_teacherLayout.setHorizontalGroup(
            tab_bar_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bar_teacherLayout.createSequentialGroup()
                .addGroup(tab_bar_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_bar_teacherLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        tab_bar_teacherLayout.setVerticalGroup(
            tab_bar_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bar_teacherLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        getContentPane().add(tab_bar_teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 290, 650));

        tab_bar_student.setBackground(new java.awt.Color(23, 35, 51));
        tab_bar_student.setPreferredSize(new java.awt.Dimension(300, 650));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Kết Quả Học Tập");
        jLabel12.setToolTipText("");

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(8, 0));

        tab_class1.setBackground(new java.awt.Color(102, 102, 102));
        tab_class1.setAlignmentX(15.0F);
        tab_class1.setAlignmentY(15.0F);
        tab_class1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_class1.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_class1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_class1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_class1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_class1MouseExited(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Kết quả học tập");

        javax.swing.GroupLayout tab_class1Layout = new javax.swing.GroupLayout(tab_class1);
        tab_class1.setLayout(tab_class1Layout);
        tab_class1Layout.setHorizontalGroup(
            tab_class1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_class1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_class1Layout.setVerticalGroup(
            tab_class1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_class1);

        tab_class2.setBackground(new java.awt.Color(102, 102, 102));
        tab_class2.setAlignmentX(15.0F);
        tab_class2.setAlignmentY(15.0F);
        tab_class2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_class2.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_class2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_class2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_class2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_class2MouseExited(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Đăng ký môn học");

        javax.swing.GroupLayout tab_class2Layout = new javax.swing.GroupLayout(tab_class2);
        tab_class2.setLayout(tab_class2Layout);
        tab_class2Layout.setHorizontalGroup(
            tab_class2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_class2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_class2Layout.setVerticalGroup(
            tab_class2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_class2);

        tab_remark3.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark3.setAlignmentX(15.0F);
        tab_remark3.setAlignmentY(15.0F);
        tab_remark3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark3.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_remark3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_remark3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_remark3MouseExited(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaint_icon.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Phúc khảo");

        javax.swing.GroupLayout tab_remark3Layout = new javax.swing.GroupLayout(tab_remark3);
        tab_remark3.setLayout(tab_remark3Layout);
        tab_remark3Layout.setHorizontalGroup(
            tab_remark3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_remark3Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_remark3Layout.setVerticalGroup(
            tab_remark3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark3);

        tab_remark5.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark5.setAlignmentX(15.0F);
        tab_remark5.setAlignmentY(15.0F);
        tab_remark5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark5.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark5.setOpaque(false);

        javax.swing.GroupLayout tab_remark5Layout = new javax.swing.GroupLayout(tab_remark5);
        tab_remark5.setLayout(tab_remark5Layout);
        tab_remark5Layout.setHorizontalGroup(
            tab_remark5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark5Layout.setVerticalGroup(
            tab_remark5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark5);

        tab_remark6.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark6.setAlignmentX(15.0F);
        tab_remark6.setAlignmentY(15.0F);
        tab_remark6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark6.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark6.setOpaque(false);

        javax.swing.GroupLayout tab_remark6Layout = new javax.swing.GroupLayout(tab_remark6);
        tab_remark6.setLayout(tab_remark6Layout);
        tab_remark6Layout.setHorizontalGroup(
            tab_remark6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark6Layout.setVerticalGroup(
            tab_remark6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark6);

        tab_remark7.setBackground(new java.awt.Color(102, 102, 102));
        tab_remark7.setAlignmentX(15.0F);
        tab_remark7.setAlignmentY(15.0F);
        tab_remark7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_remark7.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_remark7.setOpaque(false);

        javax.swing.GroupLayout tab_remark7Layout = new javax.swing.GroupLayout(tab_remark7);
        tab_remark7.setLayout(tab_remark7Layout);
        tab_remark7Layout.setHorizontalGroup(
            tab_remark7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        tab_remark7Layout.setVerticalGroup(
            tab_remark7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_remark7);

        ChangePassword.setBackground(new java.awt.Color(102, 102, 102));
        ChangePassword.setAlignmentX(15.0F);
        ChangePassword.setAlignmentY(15.0F);
        ChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ChangePassword.setMinimumSize(new java.awt.Dimension(64, 64));
        ChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseExited(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_icon.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Đổi mật khẩu");

        javax.swing.GroupLayout ChangePasswordLayout = new javax.swing.GroupLayout(ChangePassword);
        ChangePassword.setLayout(ChangePasswordLayout);
        ChangePasswordLayout.setHorizontalGroup(
            ChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        ChangePasswordLayout.setVerticalGroup(
            ChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(ChangePassword);

        tab_logout2.setBackground(new java.awt.Color(102, 102, 102));
        tab_logout2.setAlignmentX(15.0F);
        tab_logout2.setAlignmentY(15.0F);
        tab_logout2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_logout2.setMinimumSize(new java.awt.Dimension(64, 64));
        tab_logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_logout2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab_logout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab_logout2MouseExited(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_icon.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Đăng xuất");

        javax.swing.GroupLayout tab_logout2Layout = new javax.swing.GroupLayout(tab_logout2);
        tab_logout2.setLayout(tab_logout2Layout);
        tab_logout2Layout.setHorizontalGroup(
            tab_logout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_logout2Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab_logout2Layout.setVerticalGroup(
            tab_logout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel6.add(tab_logout2);

        javax.swing.GroupLayout tab_bar_studentLayout = new javax.swing.GroupLayout(tab_bar_student);
        tab_bar_student.setLayout(tab_bar_studentLayout);
        tab_bar_studentLayout.setHorizontalGroup(
            tab_bar_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bar_studentLayout.createSequentialGroup()
                .addGroup(tab_bar_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_bar_studentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        tab_bar_studentLayout.setVerticalGroup(
            tab_bar_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bar_studentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        getContentPane().add(tab_bar_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_classMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_classMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_class")) {
            return;
        }
        setColor(tab_class);

    }//GEN-LAST:event_tab_classMouseEntered

    private void tab_classMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_classMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_class")) {
            return;
        }
        resetColor(tab_class);

    }//GEN-LAST:event_tab_classMouseExited

    private void tab_classMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_classMouseClicked
        // TODO add your handling code here:
        setVisibleTabs(classTabs);
        setColor(tab_class);
        resetAllColor(tab_class);
        this.currentTabs = "tab_class";
        pack();
    }//GEN-LAST:event_tab_classMouseClicked

    private void tab_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scheduleMouseClicked
        // TODO add your handling code here:
        setVisibleTabs(scheduleTabs);
        setColor(tab_schedule);
        resetAllColor(tab_schedule);
        this.currentTabs = "tab_schedule";
        pack();
    }//GEN-LAST:event_tab_scheduleMouseClicked

    private void tab_scheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scheduleMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_schedule")) {
            return;
        }
        setColor(tab_schedule);
    }//GEN-LAST:event_tab_scheduleMouseEntered

    private void tab_scheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scheduleMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_schedule")) {
            return;
        }
        resetColor(tab_schedule);
    }//GEN-LAST:event_tab_scheduleMouseExited

    private void tab_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_studentMouseClicked
        // TODO add your handling code here:
        setVisibleTabs(studentTabs);
        setColor(tab_student);
        resetAllColor(tab_student);
        this.currentTabs = "tab_student";
        pack();
    }//GEN-LAST:event_tab_studentMouseClicked

    private void tab_studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_studentMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_student")) {
            return;
        }
        setColor(tab_student);
    }//GEN-LAST:event_tab_studentMouseEntered

    private void tab_studentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_studentMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_student")) {
            return;
        }
        resetColor(tab_student);
    }//GEN-LAST:event_tab_studentMouseExited

    private void tab_scoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scoreMouseClicked
        // TODO add your handling code here:
        setVisibleTabs(scoresTabs);
        setColor(tab_score);
        resetAllColor(tab_score);
        this.currentTabs = "tab_score";
        pack();
    }//GEN-LAST:event_tab_scoreMouseClicked

    private void tab_scoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scoreMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_score")) {
            return;
        }
        setColor(tab_score);
    }//GEN-LAST:event_tab_scoreMouseEntered

    private void tab_scoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_scoreMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_score")) {
            return;
        }
        resetColor(tab_score);
    }//GEN-LAST:event_tab_scoreMouseExited

    private void tab_remarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remarkMouseClicked
        // TODO add your handling code here:
        setVisibleTabs(remarkTabs);
        setColor(tab_remark);
        resetAllColor(tab_remark);
        this.currentTabs = "tab_remark";
        pack();
    }//GEN-LAST:event_tab_remarkMouseClicked

    private void tab_remarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remarkMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_remark")) {
            return;
        }
        setColor(tab_remark);
    }//GEN-LAST:event_tab_remarkMouseEntered

    private void tab_remarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remarkMouseExited
        // TODO add your handling code here:
        if(currentTabs.equals("tab_remark")) {
            return;
        }
        resetColor(tab_remark);
    }//GEN-LAST:event_tab_remarkMouseExited

    private void tab_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logoutMouseClicked
        // TODO add your handling code here:
        Controller.user = null;
        Controller.handleLogin();
    }//GEN-LAST:event_tab_logoutMouseClicked

    private void tab_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logoutMouseEntered
        // TODO add your handling code here:
        if(currentTabs.equals("tab_logout")) {
            return;
        }
        setColor(tab_logout);
    }//GEN-LAST:event_tab_logoutMouseEntered

    private void tab_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logoutMouseExited
        // TODO add your handling code here:
         if(currentTabs.equals("tab_logout")) {
            return;
        }
        resetColor(tab_logout);
    }//GEN-LAST:event_tab_logoutMouseExited

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        int h = evt.getComponent().getBounds().getSize().height;
        Dimension d = new Dimension(tabWidth, h);
        tab_bar_teacher.setSize(d);
        
    }//GEN-LAST:event_formComponentResized

    private void tab_class1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_class1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_class1MouseClicked

    private void tab_class1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_class1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_class1MouseEntered

    private void tab_class1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_class1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_class1MouseExited

    private void tab_remark3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remark3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_remark3MouseClicked

    private void tab_remark3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remark3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_remark3MouseEntered

    private void tab_remark3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_remark3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_remark3MouseExited

    private void ChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordMouseClicked

    private void ChangePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordMouseEntered

    private void ChangePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordMouseExited

    private void tab_logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logout2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_logout2MouseClicked

    private void tab_logout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logout2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_logout2MouseEntered

    private void tab_logout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_logout2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_logout2MouseExited

    private void teacher_change_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher_change_passMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_change_passMouseClicked

    private void teacher_change_passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher_change_passMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_change_passMouseEntered

    private void teacher_change_passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher_change_passMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_change_passMouseExited

    private void tab_class2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_class2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_class2MouseClicked

    private void tab_class2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_class2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_class2MouseEntered

    private void tab_class2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_class2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_class2MouseExited

    

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel tab_bar_student;
    private javax.swing.JPanel tab_bar_teacher;
    private javax.swing.JPanel tab_class;
    private javax.swing.JPanel tab_class1;
    private javax.swing.JPanel tab_class2;
    private javax.swing.JPanel tab_logout;
    private javax.swing.JPanel tab_logout2;
    private javax.swing.JPanel tab_remark;
    private javax.swing.JPanel tab_remark1;
    private javax.swing.JPanel tab_remark3;
    private javax.swing.JPanel tab_remark5;
    private javax.swing.JPanel tab_remark6;
    private javax.swing.JPanel tab_remark7;
    private javax.swing.JPanel tab_schedule;
    private javax.swing.JPanel tab_score;
    private javax.swing.JPanel tab_student;
    private javax.swing.JPanel teacher_change_pass;
    // End of variables declaration//GEN-END:variables
}
